### ISSUE TITLE
Kanban Board Setup

### ISSUE THREAD

**Issue by IndieCoderMM** [IndieCoderMM/e-learning-academy#16]
# Creating a Kanban board and dividing the tasks
In this capstone project, we are a group of 4 members.
- @PeteUgwu 
- @IndieCoderMM 
- @tanveerisonline 
- @tobuya 

This is the [link to Kanban Board](https://github.com/users/IndieCoderMM/projects/4).

## Screenshot
![image](https://github.com/IndieCoderMM/e-learning-academy/assets/72640048/342cb335-322c-49fc-ad09-78611cf8e037)

**Comment by mcrd25** [comment]
Hi Team, 

In my opinion, you are ready to move on to the next step! ⏭️  
Good luck! 🎉 

## Highlights
- task weights assinged equitably 👍 
- All issues have godo descriptions 👍 
- You seem to have addressed all  👍 

## Optional suggestions
- [OPTIONAL] Consider adding labels to your issues, it makes it easier to filter by different types and gives another added level of differentiation among tasks (front-end vs back-end etc.)

**P.S. Please add the project lin kto description!**

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.


Cheers and Happy coding!👏👏👏


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
